### ISSUE TITLE
Appropriate Context Hints for each platform

### ISSUE THREAD

**Issue by sjkelly** [JuliaGL/GLWindow.jl#20]
As mentioned [here](https://github.com/JuliaGL/GLWindow.jl/pull/16#issuecomment-156683860) it would be nice to have defaults that work on multiple platforms. The context hints should still be exposed so that people can have more strict criteria (for e.g. game dev if any one ever has the cajones to do that in Julia). Per @SimonDanisch 's example this might look like:
```
@linux?
const contexthints = [ ... ] 
: @windows?
const contexthints = [ ... ]
: @osx?
const contexthints = [ ... ] 
: error("Unknown Platform")

createscreen(x; contexthints=contexthints)
```

**Comment by SimonDanisch** [comment]
I guess this is sort of fixed ;)
