### ISSUE TITLE
GLWindow segfaults on `createwindow`

### ISSUE THREAD

**Issue by schlady** [JuliaGL/GLWindow.jl#22]
```julia
julia> Pkg.test("GLWindow")
INFO: Testing GLWindow

signal (11): Segmentation fault: 11
glViewport at /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib (unknown line)
createwindow at /Users/schlady/.julia/v0.4/GLWindow/src/reactglfw.jl:405
anonymous at /Users/schlady/.julia/v0.4/GLWindow/test/runtests.jl:10
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1325
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:577
jl_load at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:620
include at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1325
include_from_node1 at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1325
process_options at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
_start at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall__start_18614 at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1325
true_main at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/bin/julia (unknown line)
main at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/bin/julia (unknown line)
==============================[ ERROR: GLWindow ]===============================

failed process: Process(`/opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/bin/julia --check-bounds=yes --code-coverage=none --color=yes /Users/schlady/.julia/v0.4/GLWindow/test/runtests.jl`, ProcessSignaled(11)) [0]

================================================================================
ERROR: GLWindow had test errors
 in error at /opt/homebrew-cask/Caskroom/julia/0.4.1/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```

I am using OS X and it seems that the initialization of the underlying library `GLFW` is missing.

**Comment by SimonDanisch** [comment]
Oh, that's correct... These tests don't have a high priority for me, since they don't run on travis and I check if GLWindow and all the other packages work via my tests in GLVisualize.
Not a good excuse to not update the tests, though.

Thanks!

**Comment by schlady** [comment]
Hm, I think this only fixes symptoms.
Wouldn't it be more correct if GLWindow automatically runs `GLFW.Init()` or whatever backend it uses when it is loaded? Or should there be a `GLWindow.init()` function?
Moreover if I use GLFW directly and use their `CreateWindow` without running `GLFW.Init()` first, it will not crash. I can also call it multiple times.
My point is, it should be clear how to use GLWindow and it should never segfault for a user.
So, maybe just put a `GLFW.Init()` at the beginning of `createwindow(...)`?

**Comment by SimonDanisch** [comment]
Yeah would be nice. Although, initializing it in createwindow is not a good idea, since you might want to create multiple windows.
We thought about putting it into the `__init__` of GLFW. I can't remember anymore what spoke against it and don't find the issue anymore :D
>Moreover if I use GLFW directly and use their CreateWindow without running GLFW.Init() first, it will not crash. 

That's because it crashes at some other call. You're right, I should check if the window creation was successful.

**Comment by schlady** [comment]
Ah yes there it is: JuliaGL/GLFW.jl#66
It is only on master and didn't get a tag yet. So this should be fixed then when a new version of GLFW is released.
Sorry for the noise ;)

**Comment by SimonDanisch** [comment]
Oh no worries. Sorry for being so sloppy with GLWindow ;)
