### ISSUE TITLE
Test fail on master - type Window has no field ref

### ISSUE THREAD

**Issue by hustf** [JuliaGL/GLWindow.jl#23]
```
 julia> Pkg.test("GLWindow")
INFO: Testing GLWindow
ERROR: LoadError: type Window has no field ref
 in setindex! at dict.jl:638
 in createwindow at C:\Users\F\.julia\v0.4\GLWindow\src\reactglfw.jl:459
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:280
 in _start at client.jl:378
while loading C:\Users\F\.julia\v0.4\GLWindow\test\runtests.jl, in expression starting on line 11
==================================================[ ERROR: GLWindow ]===================================================

failed process: Process(`'C:\Users\F\AppData\Local\Julia-0.4.2\bin\julia' --check-bounds=yes --code-coverage=none --color=yes 'C:\Users\F\.julia\v0.4\GLWindow\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================
ERROR: GLWindow had test errors
 in error at error.jl:21
```

I include the requirements graph below. Checked out packages are indicated with a +.

![glwindow requirements](https://cloud.githubusercontent.com/assets/13949620/12222007/ca2e864c-b7ae-11e5-86b9-0efb6016f8fe.PNG)

With GLFW on the tagged version and other packages as above:
```
julia> window = createwindow("test", 500,500, debugging = true)
ERROR: MethodError: `hasfocus` has no method matching hasfocus(::GLFW.Window, ::Bool)
```

With GLAbstraction on the tagged version instead, the error message is:
```
ERROR: LoadError: LoadError: UndefVarError: Callable not defined
 (failed to precompile GLAbstraction)
```

Would the way forward be adding those fields?

**Comment by SimonDanisch** [comment]
Thanks! I haven't realised, that GLFW has these changes already merged an tagged! But thankfully, I prepared the fixes in a branch already :)

**Comment by hustf** [comment]
Works like a charm. This can be closed!

Off topic:
I`m back to learning this suit of packages after a break; I thought 2d would be an easier start for learning Julia / gui for calculations while the real long term motivation I have for learning Julia is computing power and visualization of the models and calculation process. Perhaps I can take engineering calculations in my particular field a little bit further with these tools. If not, trying is fun, too.

There are so many starting points and directions of investigation, and nobody can learn it all. Other than Juliacon videos and the general mailing lists, would you recommend any particular book for preparing to utilize parallel computation on the video card with Julia (when you have realized the possibility?). Googling becomes very fragmented and inefficient in the long run.

**Comment by SimonDanisch** [comment]
I'm not sure what you're trying to accomplish ;)

>parallel computation on the video card 

This is still mostly language agnostic, since you would need to do this with OpenCL/CUDA/OpenGL.
Have a look at https://github.com/JuliaGPU/OpenCL.jl and any book/tutorial about OpenCL.

**Comment by hustf** [comment]
Thank you for the advice and, of course, for fixing the issue. 

I suppose by language agnostic you mean we can use Julia and those packages as a common entry point to these very language specific technologies? This will be amazing, but neither Julia or the graphic packages are not that well developed (and may never be) as to present a smooth user experience without taking the occasional peek into the gears and levers below. I see a need for more in-depth knowledge, although I hope Julia can be both pen-and-paper and babel fish in the near future. 

I'm starting off with a book about a fourth technology - with its Julia interfaces - "Interactive Computer Graphics with WebGL",  because, well, I understand the table of contents at least,  and it seems to cover more general topics.
