### ISSUE TITLE
UndefVarError: createwindow not defined

### ISSUE THREAD

**Issue by rapus95** [JuliaGL/GLWindow.jl#27]
When trying to execute GLWindow.createwindow() i get a UndefVarError: createwindow not defined.
Searching through this repository i didn't find a definition but only calls to the missing method. When searching in the history i found a commit (c529f61f204082084379129373cf96c58e67d137) which removed a function with the given name. So in case the function should be replaced by create_glcontext (which is erroring, error at the end of this text) the front page of GLWindow should be updated and it should be considered to remove the export. So is there anything I am missing (like other projects) or is it a real issue?

create_glcontext() error (this happens to result in the same error as in GLVisualize (https://github.com/JuliaGL/GLVisualize.jl/issues/60) what makes me assuming the error comes from my instance of glfw):
```
julia> GLWindow.create_glcontext()

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1b5f4600 -- glfwGetMonitorName at  (unknown line)
while loading no file, in expression starting on line 0
glfwGetMonitorName at C:\WINDOWS\SYSTEM32\glfw3.DLL (unknown line)
call at C:\Users\necka\.julia\v0.5\GLFW\src\glfw3.jl:325
primarymonitorresolution at C:\Users\necka\.julia\v0.5\GLWindow\src\core.jl:40
standard_screen_resolution at C:\Users\necka\.julia\v0.5\GLWindow\src\screen.jl:154
julia_create_glcontext_1571 at  (unknown line)
create_glcontext at C:\Users\necka\.julia\v0.5\GLWindow\src\screen.jl:191
julia_create_glcontext_1569 at  (unknown line)
jlcall_create_glcontext_1569 at  (unknown line)
jl_apply_generic at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
eval at boot.jl:263
jl_apply_generic at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
eval_user_input at REPL.jl:3
jlcall_eval_user_input_1215 at  (unknown line)
jl_apply_generic at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
anonymous at REPL.jl:92
jl_switchto at C:\Program Files\Julia\bin\libjulia.dll (unknown line)
```

**Comment by SimonDanisch** [comment]
Do have an outdated version of GLFW?

**Comment by rapus95** [comment]
i downloaded the newest glfw file 2 days ago (glfw3) and placed it in system32 and syswow64
but to ensure i remove both and download again

**Comment by SimonDanisch** [comment]
No, I mean of GLFW.jl

**Comment by rapus95** [comment]
I ckeckout'ed twice and both times it just said nothing to do. And i'm pretty sure GLFW is up to date since it works flawlessly when used standalone

**Comment by SimonDanisch** [comment]
Yeah, the api has changed... I'll update the readme!
That's how you do it now: https://github.com/JuliaGL/GLVisualize.jl/blob/master/src/renderloop.jl#L9

I'm not sure why `create_glcontext()` errors... How have you used it?

**Comment by rapus95** [comment]
well i just called it after loading GLWindow

**Comment by rapus95** [comment]
occured because primaryMonitor returned 0
thus not a problem of the library
