### ISSUE TITLE
function 'createwindow' not defined.

### ISSUE THREAD

**Issue by ZehCnaS34** [JuliaGL/GLWindow.jl#28]
ERROR: LoadError: UndefVarError: createwindow not defined
while loading /home/alex/Desktop/vim.jl, in expression starting on line 6

Not sure If I'm doing this correctly. But after looking at the runtest.jl file, I saw that createwindow was used.

**Comment by SimonDanisch** [comment]
It's `Screen("name", resolution=(10,10))` now. Or if you only want to get the GLFW window:
`create_glcontext()`
https://github.com/JuliaGL/GLWindow.jl/blob/master/src/screen.jl#L185

Sorry, I don't update this as much as I should, as I assume that people use this package only via GLVisualize ;)
