### ISSUE TITLE
invalid ASCII sequence error when monitor name is not ASCIIString 

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaGL/GLWindow.jl#31]
I got this error when I tried `glscreen()`

> ArgumentError: invalid ASCII sequence
>  in convert at ascii.jl:107
>  in call at C:\Users\Yonghee\.julia\v0.4\GLWindow\src\types.jl:99
>  in call at C:\Users\Yonghee\.julia\v0.4\GLWindow\src\types.jl:118
> ......

But CJK OS has monitor name with `UTFString` 
in my case `GLFW.GetMonitorName(GLFW.GetPrimaryMonitor())` returns "일반 PnP 모니터"

changing `immutable MonitorProperties` field `name::ASCIIString` to `name::UTF8String` worked fine for me

**Comment by SimonDanisch** [comment]
This is already solved, sorry for not tagging yet! See: https://github.com/JuliaGL/GLWindow.jl/commit/22cbb0a951611219b75587143f1d1da6d82cba69
Right now, it's probably easier to make that change yourself.
If you want to live on master with GLVisualize, checkout the README:
https://github.com/JuliaGL/GLVisualize.jl/blob/master/README.md
