### ISSUE TITLE
Pkg add fails

### ISSUE THREAD

**Issue by micage2** [JuliaGL/GLWindow.jl#61]
When trying out GLAbstraction

ERROR: The following package names could not be resolved:
 * GLWindow (not found in project, manifest or registry)

I have Python code that uses GLFW and planning to convert it to julia.
I'm trying to stay as tight to pure OpenGL as possible. So no Makie.jl.

Why isn't it possible to add GLWindow? Is is it deprecated?
Should I only use GLFW.jl?

**Comment by SimonDanisch** [comment]
> Why isn't it possible to add GLWindow? Is is it deprecated?
Yes!

> Should I only use GLFW.jl?
Yes ;)

Feel free to use the code from: https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/glwindow.jl & https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/screen.jl to update GLWindow.jl ;) 

It shouldn't be hard, to move this back into its own package and I wouldn't mind to start using that again!

**Comment by dgkf** [comment]
@SimonDanisch - It took me some time to figure out that this is deprecated and GLFW.jl should be used in its place. Perhaps it would help people navigate JuliaGL if there was some indication of the deprecation status in the README.
